version: "3.8"
services:
 build_war:
   build:
     context: .
   volumes:
     - data/:/app/target/
 tomcat:
  image: tomcat:8.5-alpine
  ports:
    - "8090:8080"
  volumes:
    - data:/usr/local/tomcat/webapps/
volumes:
  data:
